### PR TITLE
Sasha fix js docs

### PR DESCRIPTION
**Pull request by Sasha45**
tests wip

### CODE REVIEW

**Comment by Sasha45** [comment]
All tests passing 
image
image

**Comment by Sasha45** [comment]
(resolved merge conflict)

**Comment by Hunter27E** [comment]
Hey Sasha, two tests are missing from your test suite. Can you merge main into your branch, run the tests, and post those results please? I know your PR should have no effect on tests, but just to be sure.

**Review by ManitKSoni — APPROVED** [review]
just switched urls and such, so not much too comment on other than it works

**Comment by Sasha45** [comment]
image
image
image

**Review by Hunter27E — APPROVED** [review]
[x] Straightforward implementation
[x] Good design
[x] Code looks correct
[x] UI looks as intended and fits guidelines
[x] Adequate test coverage
[x] Follows coding conventions
[x] Code is commented/documented well

A lot of these are irrelevant here but still.

**Pull request merged**
