### PR TITLE
Daily over view change i17

### PR DESCRIPTION
**Pull request by Dsuzuki126**
#17 
Redesigned the add photo button to be more intuitive and obvious. The actually functionality of the adding and saving photos needs work but for another issue.
Also fixed the jest tests and made it so you can watch the tests in action

### CODE REVIEW

**Review by ManitKSoni — APPROVED** [review]
- [x] Straightforward implementation

- [ ] Good design

- [ ] Code looks correct

- [ ] UI looks as intended and fits guidelines

- [ ] Adequate test coverage

- [ ] Follows coding conventions

- [ ] Code is commented/documented well

**Review by WeMWish — DISMISSED** [review]
- [x ] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [x] Adequate test coverage
- [x] Follows coding conventions
- [x] Code is commented/documented well

**Comment by Dsuzuki126** [comment]
testcheck
testcheck

**Comment by Dsuzuki126** [comment]
testcheck
testcheck

**Review by ManitKSoni — APPROVED** [review]
- [x] Straightforward implementation

- [x] Good design

- [ ] Code looks correct

- [ ] UI looks as intended and fits guidelines

- [ ]  Adequate test coverage

- [ ]  Follows coding conventions

- [ ] Code is commented/documented well

**Pull request closed without merging**
