### PR TITLE
Hunter-HandleArbitraryURLs-i60

### PR DESCRIPTION
**Pull request by Hunter27E**
Screen Shot 2022-06-04 at 6 17 43 PM

**Note**: You'll see that I edited one of the Login tests. This was only because the 'Enter' keyboard press to login needed more time to run, so I just added a timeout. There was no error in the functionality of the app or anything.

**PR details**:
- added 404 page to direct users to when they access invalid URLs
- validate dates in URLs on the Daily/Monthly/YearlyOverview pages (if invalid, send to 404)
- 10 tests testing the functionality of sending users to 404 page

### CODE REVIEW

**Review by Sasha45 — APPROVED** [review]
- [x]  Straightforward implementation
- [x]  Good design
- [x]  Code looks correct
- [x]  UI looks as intended and fits guidelines
- [x]  Adequate test coverage
- [x]  Follows coding conventions
- [ ]  Code is commented/documented well

**Comment by Sasha45** [comment]
Can you please show a screenshot of the 404 page?

**Comment by Hunter27E** [comment]
Screen Shot 2022-06-05 at 2 16 52 PM

**Review by Hunter27E — COMMENTED** [review]
removed weird characters

**Review by Hunter27E — COMMENTED** [review]
removed some characters

**Review by Sasha45 — APPROVED** [review]

**Review by ManitKSoni — APPROVED** [review]
- [x]  Straightforward implementation
- [x]  Good design
- [x]  Code looks correct
- [x]  UI looks as intended and fits guidelines
- [x]  Adequate test coverage
- [x]  Follows coding conventions
- [x]  Code is commented/documented well

**Pull request merged**
