### PR TITLE
Mark undone alejandro 16

### PR DESCRIPTION
**Pull request by AlejandroM2000**

### CODE REVIEW

**Review by Hunter27E — APPROVED** [review]

**Review by k9kathyli — CHANGES_REQUESTED** [review]
- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [ ] Adequate test coverage
- [x] Follows coding conventions 
- [x] Code is commented/documented well
Code looks good but we actually need a test to make sure that it changes to "Mark Undone" and so on

**Comment by AlejandroM2000** [comment]
Screen Shot 2022-05-16 at 2 38 11 PM

**Comment by AlejandroM2000** [comment]
Screen Shot 2022-05-23 at 4 07 19 PM

**Review by ManitKSoni — DISMISSED** [review]

**Comment by AlejandroM2000** [comment]
Screen Shot 2022-05-23 at 4 07 19 PM

**Review by Hunter27E — APPROVED** [review]
[x] Straightforward implementation
[x] Good design
[x] Code looks correct
[x] UI looks as intended and fits guidelines
[x] Adequate test coverage
[x] Follows coding conventions
[x] Code is commented/documented well

**Review by k9kathyli — APPROVED** [review]
- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [x] Adequate test coverage
- [x] Follows coding conventions
- [x] Code is commented/documented well

**Pull request merged**
