### PR TITLE
Sasha custom elements i7

### PR DESCRIPTION
**Pull request by Sasha45**
Summary of changes:
* created custom elements (in CustomElements.js) for most of the reused elements in Index.html
* invoked these custom elements in Index.html (this file has grown considerably)
* the purpose is to move elements into HTML, and not have them dynamically created (Calendar.js now has less work to do)
* Calendar.js and IndexJS.js still provide functionality to the page (e.g. assign numbers to days in the calendar)
* using custom elements means less div spam
* this also partially addresses #22 (only on the Index page)

image
image

### CODE REVIEW

**Comment by Sasha45** [comment]
As far as I can tell, this does *NOT* conflict with Manit Hunter i23

**Review by Dsuzuki126 — APPROVED** [review]
I believe it is all good. 
I like the comments. 
Not sure if it is super important at this point, but maybe remove the comments if Manit also agrees to do so in his code review. If not b/c of time constraints, no need.

- [x] Straightforward implementation
- [x] Good design
- [ ] Code looks correct
- [ ] UI looks as intended and fits guidelines
- [ ] Adequate test coverage
- [ ] Follows coding conventions
- [ ] Code is commented/documented well

**Comment by ManitKSoni** [comment]
Presently requires a merge

**Comment by Sasha45** [comment]
> Presently requires a merge

Done

**Review by Dsuzuki126 — APPROVED** [review]
- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [x] Adequate test coverage
- [x] Follows coding conventions
- [x] Code is commented/documented well

**Review by ManitKSoni — APPROVED** [review]
- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [x] Adequate test coverage
- [x] Follows coding conventions
- [x] Code is commented/documented well

**Pull request merged**
