### PR TITLE
Issue35branch

### PR DESCRIPTION
**Pull request by PatriciaWuu**
Screen Shot 2022-06-06 at 23 34 45

### CODE REVIEW

**Review by ManitKSoni — APPROVED** [review]

**Review by Hunter27E — CHANGES_REQUESTED** [review]
- [x] Straightforward implementation
- [x]  Good design
- [x]  Code looks correct
- [x]  UI looks as intended and fits guidelines
- [x]  Adequate test coverage
- [ ]  Follows coding conventions
- [ ]  Code is commented/documented well

Please remove all unnecessary comments. Other than that this branch is ready to merge. Once you are done let us know and we will approve.

**Review by Hunter27E — DISMISSED** [review]
- [x] Straightforward implementation
- [x]  Good design
- [x]  Code looks correct
- [x]  UI looks as intended and fits guidelines
- [x]  Adequate test coverage
- [x]  Follows coding conventions
- [x]  Code is commented/documented well

**Comment by PatriciaWuu** [comment]
Screen Shot 2022-06-07 at 19 28 25

**Review by Hunter27E — APPROVED** [review]
- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [x] Adequate test coverage
- [x] Follows coding conventions
- [x] Code is commented/documented well

**Review by ManitKSoni — APPROVED** [review]

**Pull request merged**
